---
apiVersion: v1
kind: Deployment
metadata:
  name: mongo-express-deploy
  labels: 
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - image: mongo-express
          ports:
            - containerPort: 8081 
          env:
            - name: ME_CONFIG_MONGODB_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-username
            - name: ME_CONFIG_MONGODB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongoexpress-config
                  key: database_url 
---
apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-service
spec:
  selector:
    app: mongo-express
  ports:
    - port: 8081
      nodeport: 30001
      targetPort: 8081
      protocol: TCP
  type: LoadBalancer


